version: "3"
services:

  redis:
    image: redis
    expose:
      - 6379
    networks:
      - ratelimit-network

  ratelimit:
    build:
      context: ./
      dockerfile: Dockerfile-ratelimit
    expose:
      - 8080
      - 8081
      - 6070
    networks:
      - ratelimit-network
    environment:
      - USE_STATSD=false
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit
    depends_on:
     - redis

  service: 
    build:
      context: ./
      dockerfile: Dockerfile-service
    environment:
      - PORT=8888
    expose:
      - "80"
    networks:
      ratelimit-network:

  envoy:
    build:
      context: ./
      dockerfile: Dockerfile-envoy
    networks:
      - ratelimit-network
    expose:
      - "80"
      - "8090"
      - "9901"
    ports:
      - "8081:80"
      - "8090:8090"
      - "9901:9901"
    depends_on:
     - ratelimit
     - service

  # prometheus:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile-prometheus
  #   command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus
  #   networks:
  #     - ratelimit-network
  #   ports:
  #    - 9090:9090
  #   depends_on:
  #    - envoy
      
  

networks:
  ratelimit-network: